# Generated by Django 5.0.2 on 2025-03-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Максимальное количество товара в одном заказе. 0 - без ограничений.'),
        ),
    ]
